# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: custom-ublue

# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/ublue-os/base-main

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 38

# This description will be visible in the container metadata
description: jerbmega's custom ublue image

# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
#  - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  - https://copr.fedorainfracloud.org/coprs/david35mm/pamixer/repo/fedora-37/david35mm-pamixer-fedora-38.repo
  - https://copr.fedorainfracloud.org/coprs/elxreno/bees/repo/fedora-38/elxreno-bees-fedora-38.repo

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - alacritty
  - android-tools
  - arc-theme
  - bees
  - brightnessctl
  - dbus-x11
  - docker
  - docker-compose
  - dunst
  - feh
  - file-roller
  - fontawesome-fonts
  - gvfs-mtp
  - i3
  - ImageMagick
  - la-capitaine-cursor-theme
  - libadwaita
  - libvirt-client
  - libvirt-daemon-kvm
  - lightdm-gtk
  - lxappearance
  - lxqt-policykit
  - maim
  - mousepad
  - google-noto-fonts-common
  - pamixer
  - papirus-icon-theme
  - pavucontrol
  - picom
  - playerctl
  - polybar
  - python3-pip
  - redshift
  - rofi
  - tailscale
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - tumbler
  - unclutter
  - xclip
  - xfce4-settings
  - xrandr
  - virt-manager

# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - com.valvesoftware.Steam
  - org.libreoffice.LibreOffice
  - com.github.tchx84.Flatseal
